{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red39\green42\blue50;
}
{\*\expandedcolortbl;;\cssrgb\c0\c1\c1;\cssrgb\c100000\c100000\c99985\c0;\cssrgb\c20485\c21669\c25540;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf2 \cb3 ---\
- name: Installing and Launch Metricbeat\
  hosts: webservers\
  become: yes\
  tasks:\
    # Use command module\
  - name: Download metricbeat .rpm file\
    command: \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-x86_64.rpm\cf2 \cb3 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 \
\
    # Use command module\
  - name: Install metricbeat .rpm\
    command: \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 sudo rpm -vi metricbeat-7.6.1-x86_64.rpm\cf2 \cb3 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 \
\
    # Use copy module\
  - name: Drop in metricbeat.yml\
    copy:\
      src: /etc/ansible/metricbeat-config.yml\
      dest: /etc/metricbeat/metricbeat.yml\
\
    # Use command module\
  - name: Enable and Configure System Module\
    command: metricbeat modules enable docker\
\
    # Use command module\
  - name: Setup metricbeat\
    command: metricbeat setup\
\
    # Use command module\
  - name: Start metricbeat service\
    command: metricbeat -e\
\
    # Use systemd module\
  - name: Enable service metricbeat on boot\
    systemd:\
      name: metricbeat\
      enabled: yes}